version: "3.8"
services:
  health-app:
    build: ./
    container_name: "health-app"
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - ./client/.env
      - ./api/.env
      - ./.env
    # volumes:
    #   - "./:/app"
