version: "3.8"
services:
  health-app:
    build: ./client/
    container_name: "health-app"
    ports:
      # dockerPort:hostPort
      - "3000:3000"
    env_file:
      - ./client/.env
    # volumes:
    #   - "./client:/app"
  api:
    build: ./api/
    container_name: "api"
    ports:
      - "3001:3001"
    env_file:
      - ./api/.env
