version: "3.8"
services:
  health-app:
    container_name: client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
  api:
    container_name: api
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./api/.env
