version: "3.8"
services:
  health-app:
    container_name: client
    build:
      context: .
      dockerfile: ./client/Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    volumes:
      - "./client:/app/client"
  api:
    container_name: api
    build:
      context: ./api/
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    env_file:
      - ./api/.env
    volumes:
      - "./api:/app"
      - "/app/node_modules"
