name: Lint Client
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
