name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Start local backend
        run: cd api && npm install && npm run start
        env:
          MONGO_URL: ${{secrets.MONGO_URL}}
          JWTKEY: ${{secrets.JWTKEY}}
      - name: Install dependencies
        run: cd client && npm ci
      - name: Install Playwright Browsers
        run: cd client && npx playwright install --with-deps
      - name: Run Playwright tests
        run: cd client && ls -a && npx playwright test
        env:
          TEST_USER: ${{secrets.TEST_USER}}
          TEST_USER_PASS: ${{secrets.TEST_USER_PASS}}
          REACT_APP_BACKEND_URL: ${{secrets.REACT_APP_BACKEND_URL}}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
